{
  if (response.isCommitted()) {
    logger.log(Level.WARNING,"Caught exception, but response already commited. Not sending error message based on exception",e);
  }
 else {
    final String message;
    if (e instanceof AccessDeniedException) {
      message="{\"status\":\"error\", \"error\":\"" + CloudifyErrorMessages.NO_PERMISSION_ACCESS_DENIED.getName() + "\"}";
    }
 else     if (e instanceof BadCredentialsException) {
      message="{\"status\":\"error\", \"error\":\"" + CloudifyErrorMessages.BAD_CREDENTIALS.getName() + "\"}";
    }
 else {
      logger.log(Level.WARNING,"An unexpected error was thrown: " + e.getMessage(),e);
      Map<String,Object> restErrorMap=RestUtils.verboseErrorStatus(CloudifyErrorMessages.GENERAL_SERVER_ERROR.getName(),ExceptionUtils.getStackTrace(e),e.getMessage());
      message=new ObjectMapper().writeValueAsString(restErrorMap);
    }
    final ServletOutputStream outputStream=response.getOutputStream();
    logger.log(Level.SEVERE,"caught exception. Sending response message " + message,e);
    final byte[] messageBytes=message.getBytes();
    outputStream.write(messageBytes);
  }
}
