{
  try {
    deleteVolume(volumeId);
  }
 catch (  Exception e) {
    logger.log(Level.WARNING,"Volume Provisioning failed. " + "An error was encountered while trying to delete the new volume ( " + volumeId + "). Error was: "+ e.getMessage(),e);
  }
}
